
<span class="rating">  
  <?php for ($i=5; $i >= 1; $i--): ?>
    <input type="radio" val="<?php echo $i?>" class="rating-input" id="rating-input-1-<?php echo $i?>" name="rating-input-1">
    <label for="rating-input-1-<?php echo $i?>" class="rating-star"></label>
  <?php endfor;?>
</span>

<hr>

<input onkeyup="rating(this.value)" value="0"> 

<div class="rating-average">
  <div id="rating1" class="rating-fill-active"></div>
</div>  


<div class="row">
  <div class="col-sm-7">
    <hr/>
    <div class="review-block">
      <div class="row">
        <div class="col-sm-3">
          <img src="http://dummyimage.com/60x60/666/ffffff&text=No+Image" class="img-rounded">
          <div class="review-block-name"><a href="#">nktailor</a></div>
          <div class="review-block-date">January 29, 2016<br/>1 day ago</div>
        </div>
        <div class="col-sm-9">
          <div class="review-block-rate">
            <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
          </div>
          <div class="review-block-title">this was nice in buy</div>
          <div class="review-block-description">this was nice in buy. this was nice in buy. this was nice in buy. this was nice in buy this was nice in buy this was nice in buy this was nice in buy this was nice in buy</div>
        </div>
      </div>
      <hr/>
      <div class="row">
        <div class="col-sm-3">
          <img src="http://dummyimage.com/60x60/666/ffffff&text=No+Image" class="img-rounded">
          <div class="review-block-name"><a href="#">nktailor</a></div>
          <div class="review-block-date">January 29, 2016<br/>1 day ago</div>
        </div>
        <div class="col-sm-9">
          <div class="review-block-rate">
            <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
          </div>
          <div class="review-block-title">this was nice in buy</div>
          <div class="review-block-description">this was nice in buy. this was nice in buy. this was nice in buy. this was nice in buy this was nice in buy this was nice in buy this was nice in buy this was nice in buy</div>
        </div>
      </div>
      <hr/>
      <div class="row">
        <div class="col-sm-3">
          <img src="http://dummyimage.com/60x60/666/ffffff&text=No+Image" class="img-rounded">
          <div class="review-block-name"><a href="#">nktailor</a></div>
          <div class="review-block-date">January 29, 2016<br/>1 day ago</div>
        </div>
        <div class="col-sm-9">
          <div class="review-block-rate">
            <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
            <button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
          </div>
          <div class="review-block-title">this was nice in buy</div>
          <div class="review-block-description">this was nice in buy. this was nice in buy. this was nice in buy. this was nice in buy this was nice in buy this was nice in buy this was nice in buy this was nice in buy</div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  var cw = window.rating1.clientWidth; // save original 100% pixel width

  function rating( stars ) {
    window.rating1.style.width = Math.round(cw * (stars / 5)) + 'px';
  }

rating(0);
</script>